services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - data-pipeline-project_ea4162_airflow

  pipeline-postgres:
    image: postgres:15
    container_name: pipeline-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sales_db
    volumes:
      - pipeline_pg_data:/var/lib/postgresql/data
    networks:
      - data-pipeline-project_ea4162_airflow

volumes:
  minio_data:
  pipeline_pg_data:

networks:
  data-pipeline-project_ea4162_airflow:
    external: true
